"""create seeded core world schema

Revision ID: f930b9403130
Revises: 
Create Date: 2026-06-13 10:32:00.296147
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f930b9403130'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config_version', sa.String(length=50), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'running', 'completed', 'failed', name='experiment_status', native_enum=False), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_table('tool_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('argument_schema', sa.JSON(), nullable=False),
    sa.Column('result_schema', sa.JSON(), nullable=False),
    sa.Column('availability_rules', sa.JSON(), nullable=False),
    sa.Column('produced_event_types', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_definitions')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_tool_definitions_name'))
    )
    op.create_table('worlds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('initializing', 'ready', 'running', 'completed', 'failed', name='world_status', native_enum=False), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_worlds_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worlds')),
    sa.UniqueConstraint('experiment_id', 'name', name=op.f('uq_worlds_experiment_id'))
    )
    op.create_index(op.f('ix_worlds_experiment_id'), 'worlds', ['experiment_id'], unique=False)
    op.create_table('constitution_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('source_path', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position >= 1', name=op.f('ck_constitution_articles_position_positive')),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_constitution_articles_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constitution_articles')),
    sa.UniqueConstraint('world_id', 'position', name=op.f('uq_constitution_articles_world_id')),
    sa.UniqueConstraint('world_id', 'title', name=op.f('uq_constitution_articles_world_id'))
    )
    op.create_index(op.f('ix_constitution_articles_world_id'), 'constitution_articles', ['world_id'], unique=False)
    op.create_table('landmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_landmarks_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landmarks')),
    sa.UniqueConstraint('world_id', 'id', name='uq_landmarks_world_id_id'),
    sa.UniqueConstraint('world_id', 'name', name='uq_landmarks_world_id_name')
    )
    op.create_index(op.f('ix_landmarks_world_id'), 'landmarks', ['world_id'], unique=False)
    op.create_table('seed_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_path', sa.String(length=300), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_seed_documents_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_documents')),
    sa.UniqueConstraint('world_id', 'document_type', 'version', name=op.f('uq_seed_documents_world_id'))
    )
    op.create_index(op.f('ix_seed_documents_world_id'), 'seed_documents', ['world_id'], unique=False)
    op.create_table('simulation_clocks',
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('current_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_advanced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_simulation_clocks_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', name=op.f('pk_simulation_clocks'))
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('north_star_goal', sa.Text(), nullable=False),
    sa.Column('profile_version', sa.String(length=50), nullable=False),
    sa.Column('home_landmark_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id', 'home_landmark_id'], ['landmarks.world_id', 'landmarks.id'], name=op.f('fk_agents_world_id_landmarks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_agents_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('world_id', 'id', name='uq_agents_world_id_id'),
    sa.UniqueConstraint('world_id', 'name', name='uq_agents_world_id_name')
    )
    op.create_index(op.f('ix_agents_world_id'), 'agents', ['world_id'], unique=False)
    op.create_table('agent_states',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('current_landmark_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('active', 'idle', 'critical', 'dead', 'removed', name='agent_status', native_enum=False), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('mood', sa.String(length=200), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('knowledge', sa.Float(), nullable=False),
    sa.Column('influence', sa.Float(), nullable=False),
    sa.Column('cached_credit_balance', sa.Integer(), nullable=False),
    sa.Column('zero_energy_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cached_credit_balance >= 0', name=op.f('ck_agent_states_credit_nonnegative')),
    sa.CheckConstraint('energy >= 0 AND energy <= 100', name=op.f('ck_agent_states_energy_range')),
    sa.CheckConstraint('influence >= 0 AND influence <= 100', name=op.f('ck_agent_states_influence_range')),
    sa.CheckConstraint('knowledge >= 0 AND knowledge <= 100', name=op.f('ck_agent_states_knowledge_range')),
    sa.ForeignKeyConstraint(['world_id', 'agent_id'], ['agents.world_id', 'agents.id'], name=op.f('fk_agent_states_world_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id', 'current_landmark_id'], ['landmarks.world_id', 'landmarks.id'], name=op.f('fk_agent_states_world_id_landmarks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_agent_states_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agent_states'))
    )
    op.create_index(op.f('ix_agent_states_world_id'), 'agent_states', ['world_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('turn_type', sa.Enum('regular', 'boost', 'reaction', 'system', name='turn_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='turn_status', native_enum=False), nullable=False),
    sa.Column('tool_call_budget', sa.Integer(), nullable=False),
    sa.Column('tool_calls_used', sa.Integer(), nullable=False),
    sa.Column('context_version', sa.String(length=50), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('sequence_number >= 1', name=op.f('ck_turns_sequence_positive')),
    sa.CheckConstraint('tool_call_budget >= 0', name=op.f('ck_turns_budget_nonnegative')),
    sa.CheckConstraint('tool_calls_used <= tool_call_budget', name=op.f('ck_turns_calls_within_budget')),
    sa.CheckConstraint('tool_calls_used >= 0', name=op.f('ck_turns_calls_used_nonnegative')),
    sa.ForeignKeyConstraint(['world_id', 'agent_id'], ['agents.world_id', 'agents.id'], name=op.f('fk_turns_world_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_turns_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turns')),
    sa.UniqueConstraint('world_id', 'id', name='uq_turns_world_id_id'),
    sa.UniqueConstraint('world_id', 'sequence_number', name='uq_turns_world_sequence')
    )
    op.create_index(op.f('ix_turns_agent_id'), 'turns', ['agent_id'], unique=False)
    op.create_index(op.f('ix_turns_world_id'), 'turns', ['world_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('tool_definition_id', sa.String(length=36), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=150), nullable=False),
    sa.Column('tool_version', sa.String(length=50), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'validation_failed', 'succeeded', 'execution_failed', name='tool_call_status', native_enum=False), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('sequence_number >= 1', name=op.f('ck_tool_calls_sequence_positive')),
    sa.ForeignKeyConstraint(['tool_definition_id'], ['tool_definitions.id'], name=op.f('fk_tool_calls_tool_definition_id_tool_definitions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id', 'agent_id'], ['agents.world_id', 'agents.id'], name=op.f('fk_tool_calls_world_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id', 'turn_id'], ['turns.world_id', 'turns.id'], name=op.f('fk_tool_calls_world_id_turns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_tool_calls_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls')),
    sa.UniqueConstraint('turn_id', 'sequence_number', name=op.f('uq_tool_calls_turn_id')),
    sa.UniqueConstraint('world_id', 'id', name='uq_tool_calls_world_id_id')
    )
    op.create_index(op.f('ix_tool_calls_agent_id'), 'tool_calls', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_turn_id'), 'tool_calls', ['turn_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_world_id'), 'tool_calls', ['world_id'], unique=False)
    op.create_table('credit_ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('tool_call_id', sa.String(length=36), nullable=True),
    sa.Column('system_rule', sa.String(length=150), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('simulation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(tool_call_id IS NOT NULL AND system_rule IS NULL) OR (tool_call_id IS NULL AND system_rule IS NOT NULL)', name=op.f('ck_credit_ledger_entries_single_attribution')),
    sa.CheckConstraint('amount != 0', name=op.f('ck_credit_ledger_entries_amount_nonzero')),
    sa.ForeignKeyConstraint(['world_id', 'agent_id'], ['agents.world_id', 'agents.id'], name=op.f('fk_credit_ledger_entries_world_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id', 'tool_call_id'], ['tool_calls.world_id', 'tool_calls.id'], name=op.f('fk_credit_ledger_entries_world_id_tool_calls'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_credit_ledger_entries_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger_entries'))
    )
    op.create_index(op.f('ix_credit_ledger_entries_agent_id'), 'credit_ledger_entries', ['agent_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_entries_tool_call_id'), 'credit_ledger_entries', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_entries_world_id'), 'credit_ledger_entries', ['world_id'], unique=False)
    op.create_index('ix_credit_ledger_world_agent', 'credit_ledger_entries', ['world_id', 'agent_id'], unique=False)
    op.create_table('world_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=True),
    sa.Column('tool_call_id', sa.String(length=36), nullable=True),
    sa.Column('system_rule', sa.String(length=150), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('simulation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(tool_call_id IS NOT NULL AND system_rule IS NULL) OR (tool_call_id IS NULL AND system_rule IS NOT NULL)', name=op.f('ck_world_events_single_attribution')),
    sa.CheckConstraint('sequence_number >= 1', name=op.f('ck_world_events_sequence_positive')),
    sa.ForeignKeyConstraint(['world_id', 'tool_call_id'], ['tool_calls.world_id', 'tool_calls.id'], name=op.f('fk_world_events_world_id_tool_calls'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id', 'turn_id'], ['turns.world_id', 'turns.id'], name=op.f('fk_world_events_world_id_turns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_world_events_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_events')),
    sa.UniqueConstraint('world_id', 'sequence_number', name=op.f('uq_world_events_world_id'))
    )
    op.create_index(op.f('ix_world_events_tool_call_id'), 'world_events', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_world_events_turn_id'), 'world_events', ['turn_id'], unique=False)
    op.create_index(op.f('ix_world_events_world_id'), 'world_events', ['world_id'], unique=False)
    op.create_index('ix_world_events_world_type', 'world_events', ['world_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_world_events_world_type', table_name='world_events')
    op.drop_index(op.f('ix_world_events_world_id'), table_name='world_events')
    op.drop_index(op.f('ix_world_events_turn_id'), table_name='world_events')
    op.drop_index(op.f('ix_world_events_tool_call_id'), table_name='world_events')
    op.drop_table('world_events')
    op.drop_index('ix_credit_ledger_world_agent', table_name='credit_ledger_entries')
    op.drop_index(op.f('ix_credit_ledger_entries_world_id'), table_name='credit_ledger_entries')
    op.drop_index(op.f('ix_credit_ledger_entries_tool_call_id'), table_name='credit_ledger_entries')
    op.drop_index(op.f('ix_credit_ledger_entries_agent_id'), table_name='credit_ledger_entries')
    op.drop_table('credit_ledger_entries')
    op.drop_index(op.f('ix_tool_calls_world_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_turn_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_agent_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_turns_world_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_agent_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_agent_states_world_id'), table_name='agent_states')
    op.drop_table('agent_states')
    op.drop_index(op.f('ix_agents_world_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('simulation_clocks')
    op.drop_index(op.f('ix_seed_documents_world_id'), table_name='seed_documents')
    op.drop_table('seed_documents')
    op.drop_index(op.f('ix_landmarks_world_id'), table_name='landmarks')
    op.drop_table('landmarks')
    op.drop_index(op.f('ix_constitution_articles_world_id'), table_name='constitution_articles')
    op.drop_table('constitution_articles')
    op.drop_index(op.f('ix_worlds_experiment_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_table('tool_definitions')
    op.drop_table('experiments')
    # ### end Alembic commands ###
